# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assists', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('defences', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drops', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('throwaways', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
    ]
