# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_player_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
