# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_season_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='registration_start',
            field=models.DateTimeField(),
        ),
    ]
