# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_first_year_frisbee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('catches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assists', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('defences', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drops', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('throwaways', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='playergame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playergame',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playergame',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_year_frisbee',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='year'),
        ),
        migrations.DeleteModel(
            name='PlayerGame',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
        ),
    ]
