# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20160323_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stats_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
