# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160213_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='album',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_international',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
